### ISSUE TITLE
work fine??

### ISSUE THREAD

**Issue by eliasmoral** [danielhuici/Wallamonitor#3]
Hello, I'm trying to start the bot, but I think it doesn't work well and there are things that it doesn't send, for example I'm putting a search word, I create an ad with that word and it doesn't send it, and I don't know what it is the reason.
With the words in args.json it works from time to time but I think it leaves a lot of ads in the way. Could you help me?

**Comment by danielhuici** [comment]
Keep in mind that Wallapop won't push the ads inmediatly, and it will require 10-15 for your ad to be detected by the tool.
As far as I could check, the tool will send every single ad matching that word (typed in product_name).

Sorry for late answeing, I was on holidays at that time and for any reason GitHub didn't notify me.

**Comment by SirNoish** [comment]
Buenas, sigue funcionando? Lo estoy probando y no consigo que me devuelva nada por telegram. He creado un bot, tengo el token y creo un canal del que tengo la id y donde agrego el bot. ¿Es correcto? Gracias

**Comment by danielhuici** [comment]
Sí, sigue funcionando. ¿Puedes darme una muestra de tus parámetros JSON?

**Comment by juanlusoft** [comment]
hola, podrias crear un readme de como instalarlo? gracias!
